apiVersion: v1
kind: Service
metadata:
  name: {{ include "zen-protect.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zen-protect.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zen-protect.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
