{{- if .Values.egress.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zen-cluster.fullname" . }}-egress
  labels:
    {{- include "zen-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: egress
  {{- with .Values.egress.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

