{{- if .Values.ingester.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zen-cluster.fullname" . }}-ingester
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zen-cluster.labels" . | nindent 4 }}
    component: ingester
{{- end }}

