# Copyright 2026 Zen Mesh. All rights reserved.
#

{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "zen-lock.namespace" . }}
  labels:
    {{- include "zen-lock.labels" . | nindent 4 }}
{{- end }}

