# Copyright 2026 Zen Mesh. All rights reserved.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "zen-lock.fullname" . }}-metrics
  namespace: {{ include "zen-lock.namespace" . }}
  labels:
    {{- include "zen-lock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.webhookPort }}
      targetPort: {{ .Values.service.webhookTargetPort }}
      protocol: TCP
      name: webhook
  selector:
    {{- include "zen-lock.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zen-lock.fullname" . }}-webhook
  namespace: {{ include "zen-lock.namespace" . }}
  labels:
    {{- include "zen-lock.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
      name: webhook
  selector:
    {{- include "zen-lock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook

