# Copyright 2026 Zen Mesh. All rights reserved.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "gc-controller.fullname" . }}-metrics
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gc-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "gc-controller.selectorLabels" . | nindent 4 }}

