{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zen-lead.serviceAccountName" . }}
  namespace: {{ include "zen-lead.namespace" . }}
  labels:
    {{- include "zen-lead.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

